### ISSUE TITLE
로그인 및 인증 시도시 401 에러가 발생하도록 에러 핸들링

### ISSUE THREAD

**Issue by ksk0605** [woowacourse-teams/2024-mouda#161]
# 문제 정의

로그인 및 인증 시도시 401 에러가 발생하도록 에러 핸들링
(현재는 500 서버 에러 발송)

# 액션 아이템

- [ ] 글로벌 에러 핸들링에서 인증 예외 캐치

# 내용

결과물, 참고사항 등을 입력하세요. (ex. PR, 문서 링크)

**Comment by ay-eonii** [comment]
우왕 두근두근
