### ISSUE TITLE
모임 상세 페이지 컴포넌트 개발

### ISSUE THREAD

**Issue by cys4585** [woowacourse-teams/2024-mouda#66]
# 문제 정의

스프린트 2-2 > 모임 상세 페이지 구현을 위한 컴포넌트 개발 필요

# 액션 아이템

- [x]  모임 상세 > 헤더 내부 콘텐츠
    - [x]  제목
    - [x]  작성자
- [x]  모임 상세 > 모임 정보
- [x]  모임 상세 > 상세 설명
- [ ]  공용 글꼴 스타일 주기 (ex:title,subtitle)

# 내용

**Comment by Mingyum-Kim** [comment]
이슈 제목 컨벤션 맞춰주세요 😄
혹시 스프린트 2-2 를 표시해야할 필요가 있다면 컨벤션을 다시 논의해봐도 좋을 것 같습니다.

**Comment by cys4585** [comment]
> 이슈 제목 컨벤션 맞춰주세요 😄 혹시 스프린트 2-2 를 표시해야할 필요가 있다면 컨벤션을 다시 논의해봐도 좋을 것 같습니다.

에궁ㅠㅠ 놓쳤다
