### ISSUE TITLE
룰렛 채팅방 중복 생성 문제 수정

### ISSUE THREAD

**Issue by ksk0605** [woowacourse-teams/2024-mouda#720]
# 문제 정의

다중 서버로 인한 복수의 스케줄러로 인해 복수의 룰렛채팅방 생성 문제

# 액션 아이템

문제를 해결하기 위해 필요한 액션 아이템을 입력하세요.

- [ ]  

# 내용

결과물, 참고사항 등을 입력하세요. (ex. PR, 문서 링크)

**Comment by ay-eonii** [comment]
원인 : prod의 경우 **서버 2대 모두 스케쥴링을 돌아** 채팅룸 중복 생성
해결 : 각 서버가 **2분 간격으로 스케쥴링**하도록 변경
  - prod1 : 짝수 분(0, 2, 4, ... 58)
  - prod2: 홀수 분(1, 3, 5, ... 59)
